sudo: required

language: python

services:
  - docker

before_install:
  - docker pull mcr.microsoft.com/playwright:focal

install:
  - echo "do not do anything"

script:
  - docker build --rm -t lupohan44/steamdb_free_games_claimer:latest .

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push lupohan44/steamdb_free_games_claimer:latest;
    fi
