sudo: required

language: python

services:
  - docker

before_install:
  - docker pull mcr.microsoft.com/playwright/python:v1.23.0-focal

install:
  - echo "do not do anything"

script:
  - export APP_VERSION=$(python3 -c "from version import *; print(VERSION)")
  - docker build --rm -t lupohan44/games_hub:latest -t lupohan44/games_hub:v${APP_VERSION} .

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push lupohan44/games_hub:latest;
    docker push lupohan44/games_hub:v${APP_VERSION};
    fi
